os: linux
language: python
python:
  - "3.7"
branches:
  only:
    - master
stages:
  - name: madtornado4
jobs:
  include:
    - stage: madtornado4
      name: "madtornado4"
      env:
        - GITHUB=https://github.com/SystemLight/madtornado4
      install:
        - pip install -r requirements.txt
        - pip install setuptools
        - pip install wheel
        - pip install twine
      before_script:
        - echo before_script
        - find madtornado4/ | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf
      script:
        - echo script
      after_success:
        - echo $TRAVIS_TEST_RESULT
      after_failure:
        - echo $TRAVIS_TEST_RESULT
